const MIN = 2;
const MAX = 24;
const STRING = 'Проверяемая_строка';
const MIN_STRING_LENGTH = 20;
const MAX_STRING_LENGTH = 140;
const MAX_COUNT_OBJECTS = 25;
const MIN_RANDOM = 15;
const MAX_RANDOM = 200;
const DESCRIPTIONS = ['фото с отпуска','закат','цветы','пляж'];
const DEFAULT_SCALE = 100;


export {MIN,MAX,STRING,MIN_STRING_LENGTH,MAX_STRING_LENGTH,MAX_COUNT_OBJECTS,MIN_RANDOM,MAX_RANDOM,DESCRIPTIONS,DEFAULT_SCALE};
